# 开发环境的配置文件

server:
  port: 8080
  servlet:
    session:
      timeout: 1800 # 默认单位是秒

# mariadb 的配置文件
spring:
  datasource:
    druid:
      driver-class-name: org.mariadb.jdbc.Driver
      # 如果后端项目服务器和数据库服务器不在同一台主机，则需要修改localhost为数据库服务器ip地址
      url: jdbc:mariadb://43.142.11.118:3306/blog?characterEncoding=utf-8&useSSL=false&useTimezone=true&serverTimezone=GMT%2B8
      username: root
      password: 1259
  # 配置 redis
  redis:
    database: 1 # 对应 redis 中的 DB编号
    port: 6379
    host: 43.142.11.118
  # 配置 session
  session:
    store-type: redis # 指定你的存储类型
    redis:
      flush-mode: on_save
      namespace: spring:session # 存储在 redis 中的包名

# 配置 mybatis xml 保存路径
mybatis:
  mapper-locations: classpath:mapper/**Mapper.xml
  configuration: # 配置 mybatis 在控制台打印 sql 语句
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# 设置日志级别
logging:
  level:
    com:
      example:
        demo: debug

